#!/usr/bin/env bash

if [[ -z ${VIM_FILETYPE} ]]; then
	PL_HINT=''
else
	PL_HINT=" (vim filetype=${VIM_FILETYPE})"
fi

QUERY=$(
	cat <<EOF
Go代码中可以使用Struct Tag对结构体字段进行标注.
某些情况下, Struct Tag中标注的字段名信息可能有误, 无法匹配真实的字段名, 这通常是拷贝代码或拼写错误导致的case.
请仔细检查代码片段, 尝试发现并修复这些case, 然后完整输出修复后的代码(code only).
注意输出的代码需要保留原始缩进.

>>>>> 开始: 代码片段${PL_HINT} <<<<<
$(</dev/stdin)
>>>>> 结束: 代码片段${PL_HINT} <<<<<
EOF
)

RESULT=$(chatgpt -q "${QUERY}")

if [[ ${RESULT:0:3} == '```' ]]; then
	sed -e '1d' -e '$d' <<<"${RESULT}"
else
	cat <<<"${RESULT}"
fi
