#!/usr/bin/env bash

set -euo pipefail

FILES=$(git ls-files | eval "${1}")
if [[ -z ${FILES} ]]; then
	exit 1
fi
readarray -t FILES <<<"${FILES}"

for FILE in "${FILES[@]}"; do
	echo ''
	echo "# File \`${FILE}\`"
	if [[ ! -v DRYRUN ]]; then
		echo '```'
		cat "${FILE}"
		echo '```'
	fi
done
