#!/usr/bin/env python3

import json
import sys

if "-s" in sys.argv[1:]:
    sort_keys = True
else:
    sort_keys = False

json.dump(json.load(sys.stdin), sys.stdout, separators=(",", ":"), sort_keys=sort_keys)
