#!/usr/bin/env bash

set -euo pipefail

if [[ ${DOCKER_HOST_OS} == Darwin ]]; then
	exec ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${DOCKER_HOST_USER}@host.docker.internal" \
		'export LANG=en_US.UTF-8; exec pbpaste'
fi
