set -g default-terminal "tmux-256color"
set -g default-command "${SHELL}"
set -g default-shell "/usr/bin/zsh"

set -as terminal-features 'xterm*:extkeys'
set -as terminal-features "*-256color:RGB"
set -s extended-keys on
set -s extended-keys-format csi-u

set -g mouse on
set -g focus-events on
set -g set-clipboard off
set -g allow-passthrough on

set -g base-index 1
set -g pane-base-index 1
set -s escape-time 0

set -g mode-keys vi

unbind -T copy-mode-vi MouseDragEnd1Pane
unbind -T copy-mode-vi Space
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "xargs --null tmux send-keys -l"
bind -T prefix ] run "pbpaste | tmux load-buffer -" \; paste-buffer -p

set  -g  word-separators "`~!@#$%^&*()-_=+[{]}\|;:',<.>/? "
set  -ag word-separators '"'

bind , command-prompt -I "#W" "rename-window -- '%%'"
bind : command-prompt

bind -T copy-mode-vi : send -X jump-reverse
bind -T copy-mode-vi , command-prompt -p "(goto line)" "send -X goto-line '%%%'"

bind r move-window -r
bind N swap-window -d -t +1
bind P swap-window -d -t -1
bind X kill-window -a \; move-window -r

bind c new-window -a -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind -n C-z run "exec ~/.tmux/c-z"

set -g status-position    top
set -g status-justify     centre
set -g status-left        "#[reverse] #h "
set -g status-right       "#[reverse] %Y-%m-%d %H:%M "
set -g status-left-length  80
set -g status-right-length 80

set -wg window-status-current-format "#[reverse]#[bold] #I #W#{?window_zoomed_flag,??,} "
set -wg window-status-format         " #I #W#{?window_zoomed_flag,??,} "
set -wg window-status-separator      " "

set -g @plugin "mattdavis90/base16-tmux"
set -g @colors-base16 "gruvbox-dark-soft"

set -g @plugin "roy2220/easyjump.tmux"
set -g @easyjump-text-attrs  "\e[0m\e[38;5;245m"
set -g @easyjump-label-attrs "\e[1m\e[31m"

set -g @plugin "roy2220/easyextract.tmux"

run "exec ~/.tmux/plugins/tpm/tpm"

bind k display-popup -E -B -w 38% -h 38% -- '\
fzf \
--no-height \
--border=rounded \
--prompt='\''Word> '\'' \
--bind='\''change:unbind(change)+reload([[ {q} =~ ^[A-Z] ]] && cat ~/.local/share/words/Words.txt || cat ~/.local/share/words/words.txt)'\'' \
--bind='\''enter:become(tmux send-keys -l -- {})'\'' \
--bind='\''space:become(tmux send-keys -l -- {}" ")'\'' \
--bind=ctrl-z:ignore \
<<<'\'\'
